using AutoMapper;
using TaskManagementSystem.TaskComment.Common.Models;
using TaskManagementSystem.Domain.Entities;
using TaskManagementSystem.Domain.Interfaces;
using MediatR;
using System;
using System.Collections.Generic;
using System.Text;

namespace TaskManagementSystem.TaskComment.Features.Companies.Commands.CreateTeam
{
    public class CreateTeamCommandHandler : IRequestHandler<CreateTeamCommand, Result<Guid>>
    {
        private readonly ITeamRepository _TeamRepository;
        private readonly IMapper _mapper;

        public CreateTeamCommandHandler(ITeamRepository TeamRepository, IMapper mapper)
        {
            _TeamRepository = TeamRepository;
            _mapper = mapper;
        }

        public async Task<Result<Guid>> Handle(CreateTeamCommand request, CancellationToken cancellationToken)
        {
            var Team = _mapper.Map<Team>(request);
            // Id (BIGINT) and PublicGuid (GUID) are auto-generated by SQL Server

            await _TeamRepository.AddAsync(Team, cancellationToken);
            await _TeamRepository.SaveChangesAsync(cancellationToken);

            return Result<Guid>.Success(Team.PublicGuid);
        }
    }
}
